apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "secretsSync.fullname" . }}-config
  labels:
    app: {{ template "secretsSync.fullname" . }}
data:
{{ (.Files.Glob "files/secrets.yaml").AsConfig | indent 2 }}
