{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secretsSync.serviceAccountName" . }}
  labels:
    {{- include "secretsSync.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "secretsSync.labels" . | nindent 4 }}
  name: {{ include "secretsSync.serviceAccountName" . }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - watch
      - delete
      - update
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "secretsSync.labels" . | nindent 4 }}
  name: {{ include "secretsSync.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "secretsSync.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "secretsSync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
